name: Pull Request on Github
on: [pull_request]
jobs:
  PullRequest-GitHub:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: ${{secrets.TEST_POSTGRES_USER}}
          envkey_POSTGRES_PASSWORD: ${{secrets.TEST_POSTGRES_PASSWORD}}
          envkey_POSTGRES_DB: ${{secrets.TEST_POSTGRES_DB}}
          envkey_DATABASE_URL: ${{secrets.TEST_DATABASE_URL}}
          directory: back-end/
          file_name: .env.test
          fail_on_empty: true
      - name: Run tests
        run: docker-compose -f docker-compose-test.yml run node_sorteador_app npm run test